PAINTS_AND_POSTER = "//a[contains(text(),'Obrazy i plakaty')]"
PAINTS_ON_PLEXI = "//div[@class='col-md-3 submenu-block']//a[contains(text(),'Obrazy na pleksi')]"
POPUP = "//*[@id='welcomeNewsletterPopup']/i"

FIRST_ELEMENT = "/html/body/main/section/section/div[1]/article/figure/div/div/a/picture/img"
PRICE = "//div[1]//article[1]//figure[1]//figcaption[1]//div[1]//div[1]//div[1]//div[3]//strong[1]"

CONFIGURATION = "//button[@id='configButton']"
DROPDOWN = "//div[contains(@class,'col-xs-9')]"
DESIRED_SIZE = "//a[contains(text(),'60 x 60')]"
BUY_NOW_BUTTON = "//button[@id='buyProductButton']"
SUBMIT = "//a[@name='cart_add[submit]']"
PRICE_FROM_LIST = "//div[1]//article[1]//figure[1]//figcaption[1]//div[1]//div[1]//div[1]//div[3]"
PRODUCT_CARD_PRICE = "//section[@class='col-xs-12 col-sm-5 col-md-4 col-lg-3 col-md-push-2']//div[1]//div[1]"
ITEMS_IN_CART = "/html/body/section[1]/div/div/div/div[1]/article/div[1]/h1"
PRICE_AFTER_CONFIGURATION = "//form[@id='addToCartForm']//div//div//div//div//span[contains(text(),'287 zł')]"
PRODUCT_IN_CART_PRICE = "//div[@class='col-md-7 col-xs-12']//div[2]"
